### ISSUE TITLE
Can I use skyblue with bower?

### ISSUE THREAD

**Issue by fydot** [Stanko/skyblue#5]
Skyblue is cool !!!
How can I use it in bower ?

**Comment by Stanko** [comment]
Not yet, but I want to make a bower component. I'll try to fit it in this weekend.

**Comment by fydot** [comment]
Cool !!! Thanks a lot!

**Comment by Stanko** [comment]
SkyBlue is now available on bower.
Just use `bower install skyblue`

Cheers!

**Comment by fydot** [comment]
:+1:  cool!
