### ISSUE TITLE
Document helper classes?

### ISSUE THREAD

**Issue by rmosolgo** [Stanko/skyblue#9]
Thanks for your work on this framework! This weekend I tried using it on a just-for-fun project. I probably won't use Bootstrap again :) It has so many things that I don't use. 

I appreciated the `margin-`, `padding-` and `color-` helper classes. I think they're a big asset to your framework. Documenting them would help people use it (and make it more appealing to people who are shopping around). 

Anyways, just my impression after giving it a try, I thought I would share!

**Comment by Stanko** [comment]
Thank you very much! I love those classes myself :) I plan to make much better documentation. To be honest I was making this framework for myself, but it got much more attention when I published it on the Hacker News. 

I want to make documentation together with code snipets, similar to Bootstrap's.

**Comment by rmosolgo** [comment]
Very cool, I got wind of it from here: http://afreshcup.com/home/2015/3/10/double-shot-1486.html
